# Generated by Django 2.0.4 on 2018-05-14 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2018)),
                ('number', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterModelOptions(
            name='apiary',
            options={'ordering': ('date_created',), 'verbose_name_plural': 'Apiaries'},
        ),
        migrations.AlterModelOptions(
            name='harvest',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='hive',
            options={'ordering': ('date_created',)},
        ),
        migrations.AlterModelOptions(
            name='inspection',
            options={'ordering': ('-date',)},
        ),
        migrations.AddField(
            model_name='queen',
            name='hive',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queen', to='core.Hive'),
        ),
    ]
