# Generated by Django 2.0.4 on 2018-05-17 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180514_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hive',
            name='date_terminated',
        ),
        migrations.RemoveField(
            model_name='hive',
            name='terminated',
        ),
    ]
