# Generated by Django 2.0.4 on 2018-05-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180517_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='language',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English')], default='en', max_length=4),
        ),
    ]
