# Generated by Django 2.0.3 on 2018-03-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180329_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='temperature',
            field=models.CharField(choices=[('celsius', 'Celsius'), ('fahrenheit', 'Fahrenheit')], default='celsius', max_length=10),
        ),
    ]
