# Generated by Django 2.0.4 on 2018-04-09 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180403_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='how_much_food',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AddField(
            model_name='inspection',
            name='mite_treatment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='mites_counted',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='saw_eggs',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='gave_food',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='needs_food',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='saw_queen',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
